version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Terraform
  - package-ecosystem: "terraform"
    directory: "/docker-swarm"
    schedule:
      interval: "weekly"

  # Pip (requirements.txt)
  - package-ecosystem: "pip"
    directory: "/streamripper-next"
    schedule:
      interval: "weekly"

  # Docker
  - package-ecosystem: "docker"
    directory: "/conda-docker"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/cupsd"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/adguard"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/streamripper-next"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/geoserver-docker"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/mb-system-docker"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/streamripper"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/texlive-test"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/gmt-docker/.devcontainer"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/docker-pep/.devcontainer"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/ubuntu-dev/.devcontainer"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/latex/.devcontainer"
    schedule:
      interval: "weekly"

  # Dev Containers
  - package-ecosystem: "devcontainers"
    directory: "/gmt-docker/.devcontainer"
    schedule:
      interval: "weekly"
  - package-ecosystem: "devcontainers"
    directory: "/texlive-test/.devcontainer"
    schedule:
      interval: "weekly"
  - package-ecosystem: "devcontainers"
    directory: "/docker-pep/.devcontainer"
    schedule:
      interval: "weekly"
  - package-ecosystem: "devcontainers"
    directory: "/streamripper/.devcontainer"
    schedule:
      interval: "weekly"
  - package-ecosystem: "devcontainers"
    directory: "/ubuntu-dev/.devcontainer"
    schedule:
      interval: "weekly"
  - package-ecosystem: "devcontainers"
    directory: "/latex/.devcontainer"
    schedule:
      interval: "weekly"
