services:
  gdi_geoserver:
    image:  "docker.osgeo.org/geoserver:2.24.x"
    ports:
      - "8080:8080"
    volumes:
      - ./data:/opt/geoserver_data
    environment:
       - SKIP_DEMO_DATA=true
      # - ROOT_WEBAPP_REDIRECT=false


# Login: admin / geoserver
# Start (still):  docker-compose up -d
# Stop:               docker-compose downs