services:
  mb-system:
    build:
      context: .
    container_name: mb-system
    volumes:
      - ./data:/opt/data
    stdin_open: true # docker run -i
    tty: true        # docker run -t


# Login: admin / geoserver
# Start (still):  docker-compose up -d
# Stop:               docker-compose downs